parameters:
  name: "--"
  npdenvironments: ["dev", "tst", "uat"]

jobs:
  # Upload artifacts for non prd environments
  - ${{ each environment in parameters.npdenvironments }}:
      - job: ${{ parameters.name }}_build_for_APIM_${{ environment }}
        dependsOn: Build_Queue
        condition: and(and(succeeded(), eq(variables.isProdEnvironment, false)), or(contains(dependencies.Build_Queue.outputs['setBuildQueue.buildQueue'], '${{ parameters.name }}'), contains(dependencies.Build_Queue.outputs['setBuildQueue.buildQueue'], 'AllApis')))
        variables:
          - ${{ if eq(environment, 'sbx') }}:
              - group: Sandbox
              - name: AppinsightsName
                value: "appi-cpd-shrd-mon-sbx-we-01"
              - name: AppinsightsInstrumentationKey
                value: "74d727c4-e2d9-480f-94f9-8b9bba2fd064"
              - name: ApimPublicUrl #For enabling local debugging this local host url is used
                value: http://localhost:4200 #For enabling local debugging this local host url is used
              - name: ApimDevPortalUrl
                value: https://apim-cpd-shrd-sbx-we-01.developer.azure-api.net
              - name: MarketPlaceUrl
                value: https://sbx-marketplace.tasmu.gov.qa
              - name: MyTasmuUrl
                value: https://sbx-mytasmu.tasmu.gov.qa
              - name: OpenDataUrl
                value: https://opendata.sbx.sqcp.qa
              - name: SqcpAdminPortalUrl
                value: https://sbx-cpadmin.tasmu.gov.qa
              - name: CdnUrl
                value: https://sbx-cdntasmu.azureedge.net
              - name: AccountPortalUrl
                value: https://sbx-accounts.tasmu.gov.qa
              - name: bpm-apim-user
                value: bpmpsdevapim
              - name: b2c-tenant-id
                value: 24f9d756-bf0c-43e9-ad5e-2073ae2d6698
              - name: b2c-tenant-name
                value: tasmucpb2cnonprod
              - name: bpm-app-clientid
                value: e2528f39-d92d-4174-8d71-0a22d43a3765
              - name: ngis-app-clientid
                value: dummy
              - name: ttcc-app-clientid
                value: 46b20e84-0961-443b-a5b7-bc2ffd1ccf0b
              - name: BlockEmailDomainList
                value: test, @cosaxu.com, @xcoxc.com, @inboxmail.life
          - ${{ if eq(environment, 'dev') }}:
              - group: Dev
              - name: AppinsightsName
                value: "appi-cpd-shrd-mon-dev-we-01"
              - name: AppinsightsInstrumentationKey
                value: "c6511cbc-4f97-4beb-beb0-f260fa864f97"
              - name: ApimPublicUrl #For enabling local debugging this local host url is used
                value: http://localhost:4200 #For enabling local debugging this local host url is used
              - name: ApimDevPortalUrl
                value: https://developer.dev.sqcp.qa
              - name: MarketPlaceUrl
                value: https://marketplace.dev.sqcp.qa
              - name: MyTasmuUrl
                value: https://mytasmu.dev.sqcp.qa
              - name: OpenDataUrl
                value: https://opendata.dev.sqcp.qa
              - name: SqcpAdminPortalUrl
                value: https://cpadmin.dev.sqcp.qa
              - name: CdnUrl
                value: https://dev-cdntasmu.azureedge.net
              - name: AccountPortalUrl
                value: https://account.dev.sqcp.qa
              - name: BackOfficePortalUrl
                value: https://ordering-tool.dev.sqcp.qa
              - name: bpm-apim-user
                value: bpmpsdevapim
              - name: b2c-tenant-id
                value: 24f9d756-bf0c-43e9-ad5e-2073ae2d6698
              - name: b2c-tenant-name
                value: tasmucpb2cnonprod
              - name: bpm-app-clientid
                value: e2528f39-d92d-4174-8d71-0a22d43a3765
              - name: ngis-app-clientid
                value: c28623f3-4f3d-483c-942d-0f7a62c99a94
              - name: ttcc-app-clientid
                value: 46b20e84-0961-443b-a5b7-bc2ffd1ccf0b
              - name: uber-username
                value: uberadmin
              - name: uber-password
                value: U7bvr{8=Ad$rdfHG
              - name: BlockEmailDomainList
                value: test, @cosaxu.com, @xcoxc.com, @inboxmail.life
          - ${{ if eq(environment, 'tst') }}:
              - group: Tst
              - name: AppinsightsName
                value: "appi-cpd-shrd-mon-tst-we-01"
              - name: AppinsightsInstrumentationKey
                value: "c65eba81-768e-46f6-b525-cb89dd89bb9d"
              - name: ApimPublicUrl #For enabling local debugging this local host url is used
                value: http://localhost:4200 #For enabling local debugging this local host url is used
              - name: ApimDevPortalUrl
                value: https://developer.tst.sqcp.qa
              - name: MarketPlaceUrl
                value: https://marketplace.tst.sqcp.qa
              - name: MyTasmuUrl
                value: https://mytasmu.tst.sqcp.qa
              - name: OpenDataUrl
                value: https://opendata.tst.sqcp.qa
              - name: SqcpAdminPortalUrl
                value: https://cpadmin.tst.sqcp.qa
              - name: CdnUrl
                value: https://tst-cdntasmu.azureedge.net
              - name: AccountPortalUrl
                value: https://account.tst.sqcp.qa
              - name: BackOfficePortalUrl
                value: https://ordering-tool.tst.sqcp.qa
              - name: bpm-apim-user
                value: bpmpststapim
              - name: b2c-tenant-id
                value: 24f9d756-bf0c-43e9-ad5e-2073ae2d6698
              - name: b2c-tenant-name
                value: tasmucpb2cnonprod
              - name: bpm-app-clientid
                value: e2528f39-d92d-4174-8d71-0a22d43a3765
              - name: ngis-app-clientid
                value: c28623f3-4f3d-483c-942d-0f7a62c99a94
              - name: ttcc-app-clientid
                value: 46b20e84-0961-443b-a5b7-bc2ffd1ccf0b
              - name: BlockEmailDomainList
                value: test, @cosaxu.com, @xcoxc.com, @inboxmail.life
          - ${{ if eq(environment, 'tra') }}:
              - group: tra
              - name: AppinsightsName
                value: "appi-cpd-shrd-mon-tra-we-01"
              - name: AppinsightsInstrumentationKey
                value: "bff0f909-247d-4e36-8070-806c0c704d2e"
              - name: ApimPublicUrl
                value: https://api.trn.sqcp.qa
              - name: ApimDevPortalUrl
                value: https://developer.trn.sqcp.qa
              - name: MarketPlaceUrl
                value: https://marketplace.trn.sqcp.qa
              - name: MyTasmuUrl
                value: https://mytasmu.trn.sqcp.qa
              - name: OpenDataUrl
                value: https://opendata.trn.sqcp.qa
              - name: SqcpAdminPortalUrl
                value: https://cpadmin.trn.sqcp.qa
              - name: CdnUrl
                value: https://tra-cdntasmu.azureedge.net
              - name: AccountPortalUrl
                value: https://account.trn.sqcp.qa
              - name: bpm-apim-user
                value: bpmpststapim
              - name: b2c-tenant-id
                value: 24f9d756-bf0c-43e9-ad5e-2073ae2d6698
              - name: b2c-tenant-name
                value: tasmucpb2cnonprod
              - name: bpm-app-clientid
                value: e2528f39-d92d-4174-8d71-0a22d43a3765
              - name: ngis-app-clientid
                value: dummy
              - name: ttcc-app-clientid
                value: dummy
              - name: BlockEmailDomainList
                value: test, @cosaxu.com, @xcoxc.com, @inboxmail.life
          - ${{ if eq(environment, 'uat') }}:
              - group: uat
              - name: AppinsightsName
                value: "appi-cpd-shrd-mon-uat-we-01"
              - name: AppinsightsInstrumentationKey
                value: "eccbcb6c-cb83-4805-9113-8f9f820c94f4"
              - name: ApimPublicUrl
                value: https://api.uat.sqcp.qa
              - name: ApimDevPortalUrl
                value: https://developer.uat.sqcp.qa
              - name: MarketPlaceUrl
                value: https://marketplace.uat.sqcp.qa
              - name: MyTasmuUrl
                value: https://mytasmu.uat.sqcp.qa
              - name: OpenDataUrl
                value: https://opendata.uat.sqcp.qa
              - name: SqcpAdminPortalUrl
                value: https://cpadmin.uat.sqcp.qa
              - name: CdnUrl
                value: https://uat-cdntasmu.azureedge.net
              - name: AccountPortalUrl
                value: https://account.uat.sqcp.qa
              - name: BackOfficePortalUrl
                value: https://ordering-tool.uat.sqcp.qa
              - name: bpm-apim-user
                value: bpmpsuatapim
              - name: b2c-tenant-id
                value: 24f9d756-bf0c-43e9-ad5e-2073ae2d6698
              - name: b2c-tenant-name
                value: tasmucpb2cnonprod
              - name: bpm-app-clientid
                value: e2528f39-d92d-4174-8d71-0a22d43a3765
              - name: ngis-app-clientid
                value: c28623f3-4f3d-483c-942d-0f7a62c99a94
              - name: ttcc-app-clientid
                value: 46b20e84-0961-443b-a5b7-bc2ffd1ccf0b
              - name: uber-username
                value: uberadmin
              - name: uber-password
                value: U7bvr{8=Ad$rdfHG
              - name: BlockEmailDomainList
                value: test, @cosaxu.com, @xcoxc.com, @inboxmail.life
        steps:
          - task: UseDotNet@2
            displayName: $(Environment) Use Dotnet 2.1
            inputs:
              packageType: sdk
              version: 2.1.x
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - task: PowerShell@2
            displayName: "Create repository folder (workaround)"
            inputs:
              targetType: inline
              script: |
                New-Item -Path . -Name "$(Build.Repository.Name)" -Force -ItemType "directory" # Equals "self"
              pwsh: true

          - task: PowerShell@2
            displayName: "Create repository folder for devops kit(workaround)"
            inputs:
              targetType: inline
              script: |
                New-Item -Path . -Name "apim-devopskit" -Force -ItemType "directory" # Equals "self"
              pwsh: true

          - checkout: apis-repo # self represents the repo where the initial Pipelines YAML file was found
            clean: true # whether to fetch clean each time
            path: apis-repo

          - checkout: apim-devopskit # self represents the repo where the initial Pipelines YAML file was found
            clean: true # whether to fetch clean each time
            path: apim-devopskit

          - task: CmdLine@2
            displayName: $(Environment) Create APIMTemplate Tool
            inputs:
              script: |
                dotnet restore
                dotnet pack -c Release
                cd $(Agent.BuildDirectory)/apis-repo/pipelines/APIM/src
                dotnet new tool-manifest
                dotnet tool install --add-source "$(Agent.BuildDirectory)/apim-devopskit/src/APIM_ARMTemplate/apimtemplate/bin/Release" apimtemplate
              workingDirectory: "$(Agent.BuildDirectory)/apim-devopskit/src/APIM_ARMTemplate/apimtemplate"
              failOnStderr: true

          - task: CmdLine@2
            displayName: $(Environment) Generate ARM templates using Tool
            inputs:
              script: 'dotnet tool run apim-templates create --appInsightsInstrumentationKey $(AppinsightsInstrumentationKey) --appInsightsName  $(AppinsightsName) --namedValues "Azure-Search-Key|$(Azure-Search-Key);Bot-Directline-Key|$(Bot-Directline-Key);ApimPublicUrl|$(ApimPublicUrl);ApimDevPortalUrl|$(ApimDevPortalUrl);MarketPlaceUrl|$(MarketPlaceUrl);MyTasmuUrl|$(MyTasmuUrl);OpenDataUrl|$(OpenDataUrl);SqcpAdminPortalUrl|$(SqcpAdminPortalUrl);CdnUrl|$(CdnUrl);AccountPortalUrl|$(AccountPortalUrl);BackOfficePortalUrl|$(BackOfficePortalUrl);bpm-apim-user|$(bpm-apim-user);bpm-apim-pwd|$(BPM-APIM-Password);b2c-tenant-id|$(b2c-tenant-id);b2c-tenant-name|$(b2c-tenant-name);bpm-app-clientid|$(bpm-app-clientid);ngis-app-clientid|$(ngis-app-clientid);ngis-app-token|$(NGIS-App-Token);ttcc-app-clientid|$(ttcc-app-clientid);uber-username|$(uber-username);uber-password|$(uber-password);BlockEmailDomainList|$(BlockEmailDomainList);" --configFile "./Input/valid.yml" --backendurlconfigFile "./Input/TemplateAndParameters/$(Environment)/BackendUrlParameters.json" --preferredAPIsForDeployment ${{ parameters.name }}  --apimNameValue $(Environment)${{ parameters.name }}we01'
              workingDirectory: "$(Agent.BuildDirectory)/apis-repo/pipelines/APIM/src"
              failOnStderr: true

          - task: AzureCLI@1
            displayName: $(Environment) Copy Module to $(componentStorageAccountNameNpd)
            inputs:
              azureSubscription: $(serviceConnectionNpd)
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob upload-batch --source "$(Agent.BuildDirectory)/apis-repo/pipelines/APIM/src/Output" --destination "$(componentStorageContainerName)/APIMConfig/ARM/$(Environment)/${{ parameters.name }}" --account-name "$(componentStorageAccountNameNpd)" --subscription  "$(componentStorageAccountSubscriptionIdNpd)" --overwrite

          - task: AzureCLI@1
            displayName: $(Environment) Copy Other files in Module to $(componentStorageAccountNameNpd)
            inputs:
              azureSubscription: $(serviceConnectionNpd)
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob upload-batch --source "$(Agent.BuildDirectory)/apis-repo/pipelines/APIM/src/Input/TemplateAndParameters/$(Environment)" --destination "$(componentStorageContainerName)/APIMConfig/ARM/$(Environment)/${{ parameters.name }}" --account-name "$(componentStorageAccountNameNpd)" --subscription  "$(componentStorageAccountSubscriptionIdNpd)" --overwrite
