jobs:
  - template: build-template.yml
    parameters:
      name: GeometryFreeApi

  - template: build-template.yml
    parameters:
      name: GeometryStandardApi

  - template: build-template.yml
    parameters:
      name: GeometryPremiumApi

  - template: build-template.yml
    parameters:
      name: GeofencingFreeApi

  - template: build-template.yml
    parameters:
      name: GeofencingStandardApi

  - template: build-template.yml
    parameters:
      name: GeofencingPremiumApi

  - template: build-template.yml
    parameters:
      name: GeotaggingStandardApi

  - template: build-template.yml
    parameters:
      name: GeotaggingPremiumApi

  - template: build-template.yml
    parameters:
      name: HeatMapPremiumServiceApi

  - template: build-template.yml
    parameters:
      name: HotspotPremiumServiceApi
