parameters:
  - name: name
    type: string
    default: ""
  - name: solutionPath
    type: string
    default: ""
  - name: feedURL
    type: string
jobs:
  - job: ${{ parameters.name }}
    variables:
      dockerfilePath: ${{ parameters.solutionPath }}/Dockerfile
      imageRepository: $(namespace)/${{ parameters.name }}
    steps:
      - checkout: web-apps
        clean: true 
        path: TASMU Central Platform/web-apps
        
      - task: Docker@2
        displayName: Build image
        inputs:
          containerRegistry: "$(dockerRegistryServiceConnection)"
          repository: "$(imageRepository)"
          command: "build"
          Dockerfile: "$(dockerfilePath)"
          tags: "$(tag)"
          arguments: "--build-arg PAT=$(System.NugetAccessToken) --build-arg FEED_URL=${{ parameters.feedURL }}"

      - task: Docker@2
        displayName: Push image to container registry
        inputs:
          containerRegistry: "$(dockerRegistryServiceConnection)"
          repository: "$(imageRepository)"
          command: "push"
          tags: "$(tag)"
