jobs:
  - job: PublishArtifact
    displayName: Publish Artifact
    pool:
      vmImage: $(vmImage)
      
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: PublishBuildArtifacts@1
        displayName: Publish $(moduleName) Artifacts
        inputs:
          PathtoPublish: $(modulePath)
          ArtifactName: $(moduleName)-$(moduleVersion)

  - job: PublishComponentPrd
    displayName: Publish Component Prd
    pool:
      vmImage: $(vmImage)
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: CopyFiles@2
        displayName: Filter folders
        inputs:
          Contents: |
            Modules/ARM/$(moduleName)/$(moduleVersion)/**
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: AzureCLI@1
        displayName: Create container $(componentStorageContainerName)
        inputs:
          azureSubscription: $(serviceConnectionPrd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNamePrd)" --subscription "$(componentStorageAccountSubscriptionIdPrd)"           
        
      - task: AzureCLI@1
        displayName: Copy Module to $(componentStorageAccountNamePrd)
        inputs:
          azureSubscription: $(serviceConnectionPrd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNamePrd)" --subscription  "$(componentStorageAccountSubscriptionIdPrd)" --overwrite
