parameters:
  templateFile: $(modulePath)/deploy.json
  parametersFile: $(modulePath)/Parameters/parameters.json

jobs:
- job: ValidateModule
  displayName: Validate Module
  pool:
    name: $(PoolName)
    #vmImage: $(vmImage)
  variables:
  - template: pipeline.variables.yml
  steps:
    - task: PowerShell@2 #Run Pester
      displayName: Test Module $(moduleName) (Pester)
      inputs:
        targetType: inline
        script: |
          Install-Module Pester -Force -ErrorAction Stop

          $PesterSettings  = @{
            Script       = "$(System.DefaultWorkingDirectory)/$(modulePath)/Tests/*.tests.ps1"
            OutputFile   = "$(Agent.WorkFolder)/testsresult.xml"
            OutputFormat = "NUnitXml"
            EnableExit   = $true
            Verbose      = $true
          }

          Invoke-Pester @PesterSettings
        pwsh: true

    - task: PublishTestResults@2 #Publish test results
      displayName: Publish Test Results
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: $(Agent.WorkFolder)/testsresult.xml

    - task: AzurePowerShell@4 #Test deployment 
      displayName: 'Validate $(moduleName) in $(resourceGroupName) via $(serviceconnection)'
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        inline: |
            if (-not (Get-AzResourceGroup -Name $(resourceGroupName) -ErrorAction SilentlyContinue))
            {
              New-AzResourceGroup -Name $(resourceGroupName) -Location "$(location)"
            }

            $ValidationErrors = $null

            $DeploymentInputs = @{
              ResourceGroupName     = "$(resourceGroupName)"
              TemplateFile          = "$(Build.Repository.LocalPath)/${{ parameters.templateFile }}"
              TemplateParameterFile = "$(Build.Repository.LocalPath)/${{ parameters.parametersFile }}"
              Mode                  = "Incremental"
              Verbose               = $true
              OutVariable           = "ValidationErrors"
            }
            
            Test-AzResourceGroupDeployment @DeploymentInputs

            if ($ValidationErrors)
            {
                foreach ($message in $ValidationErrors.Details)
                {
                    Write-Error $message.Message
                }
                Write-Error "Template is not valid."
            }
        azurePowerShellVersion: LatestVersion
