# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'sqcp-ado-spn-hub-qc'
    subscriptionId: '4e865dba-bf2f-463a-a957-c69f5fb32ec5'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-tasmu-health'
    location: 'Qatar Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'Modules/ARM/HealthRules/HealthRules'
    csmParametersFileLink: 'Modules/ARM/HealthRules/parameters'
    deploymentMode: 'Complete'