define([], function () {
  return {
    "PropertyPaneDescription": "الضبط",
    "BasicGroupName": "خصائص جزء الموقع الإلكتروني",
    "WebPartTitleFieldLabel": "عنوان جزء الموقع الإلكتروني (العربي)",
    "WebPartTitleArFieldLabel": "عنوان جزء الموقع الإلكتروني (العربي)",
    "ViewModeFieldLabel": "الرأي/ عرض",
    "ListPickerFieldLabel": "قائمة المهام",
    "TranslationTaskContentTypeFieldLabel": "نوع محتوى مهام الترجمة",
    "ApprovalTaskContentTypeFieldLabel": "نوع محتوى مهام الاعتماد",
    "ItemsPerPageFieldLabel": "العناصر الموجودة بالصفحة",
    "SeeAllLinkLabelField": "الإطلاع على جميع الروابط",
    "AllRequestsPivotHeader": "جميع الطلبات",
    "PendingApprovalsPivotHeader": "الاعتمادات الجارية",
    "TranslationRequestsPivotHeader": "طلبات الترجمة",
    "HistoryPivotHeader": "السجل",
    "CompactViewLabel": "المدمج",
    "DetailedViewLabel": "المفصّل",
    "StartLabel": "البدء",
    "FinishLabel": "الانتهاء",
    "ApproveLabel": "اعتماد",
    "RejectLabel": "رفض",
    "TaskTitleLabel": "اسم المهمة",
    "PreviewUrlLabel": "معاينة الرابط الإنجليزي",
    "PreviewUrlArLabel": "معاينة الرابط العربي",
    "ListNameLabel": "اسم القائمة",
    "ModifiedLabel": "تاريخ التعديل",
    "ActionLabel": "الإجراء",
    "TaskCommentsLabel": "الملاحظات",
    "ActionByLabel": "اتخذ الإجراء بواسطة",
    "NoDataFoundLabel": "لا توجد مهام غير مكتملة",
    "ConfirmButtonLabel": "تأكيد",
    "CancelButtonLabel": "إلغاء",
    "CommentsLabel": "التعليقات (اختياري)",
    "ConfirmationHeaderLabel": "يرجى التأكد من تدقيق المحتوى قبل تقديمه",
    "ConfirmationTextLabel": "يرجى التأكد من مراجعة المحتوى قبل الإرسال",
    "SeeAllLabel": "مشاهدة الكل",
    "FirstPageLabel": "الصفحة الأولى",
    "NextPageLabel": "الصفحة التالية",
    "LastPageLabel": "الصفحة الأخيرة",
    "PreviousPageLabel": "الصفحة السابقة"
  }
});
