define([], function () {
  return {
    "PropertyPaneDescription": "Configuration",
    "BasicGroupName": "Web Part Properties",
    "WebPartTitleFieldLabel": "Web Part Title",
    "WebPartTitleArFieldLabel": "Web Part Title (Arabic)",
    "ViewModeFieldLabel": "Select View Mode",
    "ListPickerFieldLabel": "Select Tasks List",
    "TranslationTaskContentTypeFieldLabel": "Translation Task Content Type",
    "ApprovalTaskContentTypeFieldLabel": "Approval Task Content Type",
    "ItemsPerPageFieldLabel": "Items per page",
    "SeeAllLinkLabelField": "See All Link",
    "AllRequestsPivotHeader": "All Requests",
    "PendingApprovalsPivotHeader": "Pending Approvals",
    "TranslationRequestsPivotHeader": "Translation Requests",
    "HistoryPivotHeader": "History",
    "CompactViewLabel": "Compact",
    "DetailedViewLabel": "Detailed",
    "StartLabel": "Start",
    "FinishLabel": "Finish",
    "ApproveLabel": "Approve",
    "RejectLabel": "Reject",
    "TaskTitleLabel": "Task Title",
    "PreviewUrlLabel": "Preview URL(Eng)",
    "PreviewUrlArLabel": "Preview URL(Arabic)",
    "ListNameLabel": "List Name",
    "ModifiedLabel": "Modified Date",
    "ActionLabel": "Action",
    "TaskCommentsLabel": "Task Comments",
    "ActionByLabel": "Action By",
    "NoDataFoundLabel": "No Pending Tasks",
    "ConfirmButtonLabel": "Confirm",
    "CancelButtonLabel": "Cancel",
    "CommentsLabel": "Comments (Optional)",
    "ConfirmationHeaderLabel": "Confirmation",
    "ConfirmationTextLabel": "Please make sure to review the content before submitting",
    "SeeAllLabel": "See all",
    "FirstPageLabel": "First Page",
    "NextPageLabel": "Next Page",
    "LastPageLabel": "Last Page",
    "PreviousPageLabel": "Previous Page"
  }
});
