apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name}}  
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version}}
    aadpodidbinding: {{ .Values.podIdentity}}        
spec:
  selector:
      matchLabels:
        app: {{ .Chart.Name}}
  replicas: {{ .Values.replicaCount}}
  template:
      metadata:
        labels:
            app: {{ .Chart.Name}}
            aadpodidbinding: {{ .Values.podIdentity}}     
        annotations:
          dapr.io/enabled: "true"
          dapr.io/id: {{ .Values.daprio.id}}  
          dapr.io/port: {{ .Values.daprio.port}}  
          dapr.io/log-level: {{ .Values.daprio.loglevel}}  
          dapr.io/log-as-json: {{ .Values.daprio.logasjson}}                        
          dapr.io/sidecar-cpu-limit: {{ .Values.daprio.sidecarcpulimit}}  
          dapr.io/sidecar-memory-limit: {{ .Values.daprio.sidecarmemorylimit}}  
          dapr.io/sidecar-cpu-request: {{ .Values.daprio.sidecarcpurequest}}  
          dapr.io/sidecar-memory-request: {{ .Values.daprio.sidecarmemoryrequest}}        
      spec:
        nodeSelector: 
          agentpool: {{ .Values.nodeSelector }}
        containers:
        - name: {{ .Chart.Name}}
          image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu}}
              memory: {{ .Values.resources.requests.memory}}
            limits:
              cpu: {{ .Values.resources.limits.cpu}}
              memory: {{ .Values.resources.limits.memory}}
          ports:
          - containerPort: {{ .Values.container.containerPort}}
          env:
          - name: ConnectionStrings__AppConfig
            value: {{ .Values.environment.ConnectionStrings__AppConfig}}
