name: CI-APIMConfig-Productization-Master-Build

resources:
  repositories:
    - repository: apim-devopskit # The name used to reference this repository in the checkout step
      type: git
      name: TASMU Central Platform/apim-devopskit
      ref: master

    - repository: apis-repo # The name used to reference this repository in the checkout step
      type: git
      name: TASMU Central Platform/apim-api-config
      ref: main

trigger: none

pool:
  name: $(poolName)

variables:
  - template: templates/globalvariables-npd.yml

jobs:
  - job: Build_Queue
    steps:
      - task: PowerShell@2
        name: setBuildQueue
        inputs:
          targetType: filePath
          filePath: "pipelines/APIM/src/Pipeline/templates/get-service-queue.ps1"
        displayName: "Get Service Build Queue"

  - template: templates/productization.yml
# Add more template jobs with parameters for other Services
