apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureassignedidentities.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  version:
    name: v1
    storedVersions: true
  names:
    kind: AzureAssignedIdentity
    plural: azureassignedidentities
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureidentitybindings.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  version:
    name: v1
    storedVersions: true
  names:
    kind: AzureIdentityBinding
    plural: azureidentitybindings
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureidentities.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  version:
    name: v1
    storedVersions: true
  names:
    kind: AzureIdentity
    singular: azureidentity
    plural: azureidentities
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azurepodidentityexceptions.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  version:
    name: v1
    storedVersions: true
  names:
    kind: AzurePodIdentityException
    singular: azurepodidentityexception
    plural: azurepodidentityexceptions
  scope: Namespaced