apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureassignedidentities.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
    "api-approved.kubernetes.io": "unapproved: This group is not approved by my organization."
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                azureIdentity:
                  type: string
                pod:
                  type: object
                  properties:
                    selector:
                      type: object
                      properties:
                        matchLabels:
                          type: object
                          additionalProperties:
                            type: string
      additionalPrinterColumns:
        - name: AzureIdentity
          type: string
          description: The Azure identity assigned to the pod
          JSONPath: .spec.azureIdentity
  names:
    kind: AzureAssignedIdentity
    plural: azureassignedidentities
scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureidentitybindings.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
    "api-approved.kubernetes.io": "unapproved: This group is not approved by my organization."
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                azureIdentity:
                  type: string
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
              required:
                - azureIdentity
                - selector
      additionalPrinterColumns:
        - name: AzureIdentity
          type: string
          description: The Azure identity to bind to the pod
          JSONPath: .spec.azureIdentity
  names:
    kind: AzureIdentityBinding
    plural: azureidentitybindings

scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureidentities.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
    "api-approved.kubernetes.io": "unapproved: This group is not approved by my organization."
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type: string
                resourceID: string
              required:
                - type
                - resourceID
      additionalPrinterColumns:
        - name: Type
          type: string
          description: The type of Azure identity
          JSONPath: .spec.type
        - name: ResourceID
          type: string
          description: The Azure resource ID of the identity
          JSONPath: .spec.resourceID
  names:
    kind: AzureIdentity
    singular: azureidentity
    plural: azureidentities

scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azurepodidentityexceptions.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
    "api-approved.kubernetes.io": "unapproved: This group is not approved by my organization."
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                podLabels:
                  type: object
                  additionalProperties:
                    type: string
              required:
                - podLabels
      additionalPrinterColumns:
        - name: PodLabels
          type: string
          description: The labels for the pods excluded from Azure Pod Identity
          JSONPath: .spec.podLabels
  names:
    kind: AzurePodIdentityException
    singular: azurepodidentityexception
    plural: azurepodidentityexceptions
  scope: Namespaced