jobs:
  - job: PublishArtifact
    displayName: Publish Artifact
    pool:
      name: $(poolName)
      
    variables:
      - template: pipeline.variables.yml
      - clientId: '029192d9-a031-4f98-84c4-b31173e991d3'
      - clientSecret: '4Tg5--4P_qNEF_RG0PN3mA_k4kJnMueufx'
      - tenantId: 'tasmucpb2cnonprod.onmicrosoft.com'
      - appClientId: '7a966e81-c9d4-4a5e-b170-d37c45e282bd'
      - appObjectId: '6cec6fe0-93fb-4d12-a549-e7cabdae890e'

    steps:
      - task: PublishBuildArtifacts@1
        displayName: Publish $(moduleName) Artifacts
        inputs:
          PathtoPublish: $(modulePath)
          ArtifactName: $(moduleName)-$(moduleVersion)

  - job: PublishComponentPrd
    displayName: Publish Component Prd
    pool:
      name: $(poolName)
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: CopyFiles@2
        displayName: Filter folders
        inputs:
          Contents: |
            Modules/ARM/$(moduleName)/$(moduleVersion)/**
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: AzureCLI@1
        displayName: Create container $(componentStorageContainerName)
        inputs:
          azureSubscription: $(serviceConnectionPrd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNamePrd)" --subscription "$(componentStorageAccountSubscriptionIdPrd)"           
        
      - task: AzureCLI@1
        displayName: Copy Module to $(componentStorageAccountNamePrd)
        inputs:
          azureSubscription: $(serviceConnectionPrd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNamePrd)" --subscription  "$(componentStorageAccountSubscriptionIdPrd)"


  - job: PublishComponentNpd
    displayName: Publish Component Npd
    pool:
      name: $(poolName)
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: CopyFiles@2
        displayName: Filter folders
        inputs:
          Contents: |
            Modules/ARM/$(moduleName)/$(moduleVersion)/**
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: AzureCLI@1
        displayName: Create container $(componentStorageContainerName)
        inputs:
          azureSubscription: $(serviceConnectionNpd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNameNpd)" --subscription "$(componentStorageAccountSubscriptionIdNpd)"           
        
      - task: AzureCLI@1
        displayName: Copy Module to $(componentStorageAccountNameNpd)
        inputs:
          azureSubscription: $(serviceConnectionNpd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNameNpd)" --subscription  "$(componentStorageAccountSubscriptionIdNpd)"