jobs:
  - job: PublishArtifact
    displayName: Publish Artifact
    pool:
      #name: $(poolName)
      vmImage: $(vmImage)
      
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: PublishBuildArtifacts@1
        displayName: Publish $(moduleName) Artifacts
        inputs:
          PathtoPublish: $(modulePath)
          ArtifactName: $(moduleName)-$(moduleVersion)

  - job: PublishComponentPrd
    displayName: Publish Component Prd
    pool:
      #name: $(poolName)
      vmImage: $(vmImage)
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: CopyFiles@2
        displayName: Filter folders
        inputs:
          Contents: |
            Modules/ARM/$(moduleName)/$(moduleVersion)/**
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: AzureCLI@1
        displayName: Create container $(componentStorageContainerName)
        inputs:
          azureSubscription: $(serviceConnectionPrd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNamePrd)" --subscription "$(componentStorageAccountSubscriptionIdPrd)"           
        
      - task: AzureCLI@1
        displayName: Copy Module to $(componentStorageAccountNamePrd)
        inputs:
          azureSubscription: $(serviceConnectionPrd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNamePrd)" --subscription  "$(componentStorageAccountSubscriptionIdPrd)"

  # - job: PublishComponentPre
  #   displayName: Publish Component Pre
  #   pool:
  #     #name: $(poolName)
  #     vmImage: $(vmImage)
  #   variables:
  #     - template: pipeline.variables.yml
  #   steps:
  #     - task: CopyFiles@2
  #       displayName: Filter folders
  #       inputs:
  #         Contents: |
  #           Modules/ARM/$(moduleName)/$(moduleVersion)/**
  #         targetFolder: $(Build.ArtifactStagingDirectory)
  #     - task: AzureCLI@1
  #       displayName: Create container $(componentStorageContainerName)
  #       inputs:
  #         azureSubscription: $(serviceConnectionPrd)
  #         scriptLocation: inlineScript
  #         inlineScript: |
  #           az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNamePre)" --subscription "$(componentStorageAccountSubscriptionIdPrd)"

  #     - task: AzureCLI@1
  #       displayName: Copy Module to $(componentStorageAccountNamePre)
  #       inputs:
  #         azureSubscription: $(serviceConnectionPrd)
  #         scriptLocation: inlineScript
  #         inlineScript: |
  #           az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNamePre)" --subscription  "$(componentStorageAccountSubscriptionIdPrd)"

  - job: PublishComponentNpd
    displayName: Publish Component Npd
    pool:
      #name: $(poolName)
      vmImage: $(vmImage)
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: CopyFiles@2
        displayName: Filter folders
        inputs:
          Contents: |
            Modules/ARM/$(moduleName)/$(moduleVersion)/**
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: AzureCLI@1
        displayName: Create container $(componentStorageContainerName)
        inputs:
          azureSubscription: $(serviceConnectionNpd)
          scriptLocation: inlineScript
          inlineScript: |
            echo "I am here"
            echo $componentStorageAccountSubscriptionIdNpd
            az storage container create --name "module" --public-access off --account-name  "stcphpltfiactstnpdqc01" --account-key "gIba1aDFPVLhtmFID+20/Ra2IBTDjhItoHitxs5JRUMpFMENjX4X3w4jVa3RrWQj0XDBzA62O8mi+ASt3s2grA==" --subscription "f9795662-4020-4ccf-ae1a-426542cab5c4"           
           #az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNameNpd)" --subscription "$(componentStorageAccountSubscriptionIdNpd)"           
        
      - task: AzureCLI@1
        displayName: Copy Module to $(componentStorageAccountNameNpd)
        inputs:
          azureSubscription: $(serviceConnectionNpd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "components/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name  "stcphpltfiactstnpdqc01" --account-key "gIba1aDFPVLhtmFID+20/Ra2IBTDjhItoHitxs5JRUMpFMENjX4X3w4jVa3RrWQj0XDBzA62O8mi+ASt3s2grA==" --subscription "f9795662-4020-4ccf-ae1a-426542cab5c4"