trigger:
  - none

variables:
  - name: PoolName
    value: "tasmumsiagents"
  - name: serviceConnection
    value: sqcp-ado-spn-pre
  - group: "Shared"

pool:
  name: $(PoolName)

stages:
  - stage: PublishArtifacts
    jobs:
    - job: PublishArtifacts
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: Scripts/KeyVault
          Contents: "**"
          TargetFolder: "$(build.artifactstagingdirectory)/scripts"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: Scripts/KeyVault
          artifact: "scripts"
          publishLocation: "pipeline"

  - stage: pre
    displayName: Add Pre-Prod Secrets
    dependsOn: PublishArtifacts
    variables:
      - group: pre
      - name: keyVaultName
        value: kv-cpp-data-pre-we-01
    jobs:
      - deployment: Deploy
        displayName: Add pre-prod Key Vault Secrets
        environment: data-pre
        strategy:
          runOnce:
            deploy:
              steps:
                - template: data-secrets-infra.yml