trigger:
  - none

variables:
  - name: PoolName
    value: "tasmumsagents"
  - name: keyVaultScriptPath
    value: Scripts/KeyVault/Set-AzureKeyVaultSecret.ps1
  - name: serviceConnection
    value: sqcp-ado-spn-dev

pool:
  name: $(PoolName)

stages:
  - stage: Sandbox
    displayName: Add Sandbox KV Secrets
    variables:
      - group: "Sandbox"
      - name: keyVaultName
        value: kv-cpd-apps-sbx-we-01
    jobs:
      - deployment: Deploy
        displayName: Add Sbx Key Vault Secrets
        environment: sbx
        strategy:
          runOnce:
            deploy:
              steps:
                - template: all-secrets.yml

  - stage: Dev
    displayName: Add Dev KV Secrets
    variables:
      - group: "Dev"
      - name: keyVaultName
        value: kv-cpd-apps-dev-we-01
    jobs:
      - deployment: Deploy
        displayName: Add dev Key Vault Secrets
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: all-secrets.yml

  - stage: Tst
    displayName: Add Tst KV Secrets
    variables:
      - group: "Tst"
      - name: keyVaultName
        value: kv-cpd-apps-tst-we-01
    jobs:
      - deployment: Deploy
        displayName: Add tst Key Vault Secrets
        environment: tst
        strategy:
          runOnce:
            deploy:
              steps:
                - template: all-secrets.yml
