trigger:
  - none

variables:
  - name: PoolName
    value: "tasmumsagents"
  - name: serviceConnection
    value: sqcp-ado-spn-dev
  - group: "Shared"

pool:
  name: $(PoolName)

stages:
  - stage: PublishArtifacts
    jobs:
    - job: PublishArtifacts
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: Scripts/KeyVault
          Contents: "**"
          TargetFolder: "$(build.artifactstagingdirectory)/scripts"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: Scripts/KeyVault
          artifact: "scripts"
          publishLocation: "pipeline"

  - stage: Sandbox
    displayName: Add Sandbox KV Secrets
    dependsOn: PublishArtifacts
    variables:
      - group: "Sandbox"
      - name: keyVaultName
        value: kv-cpd-apps-sbx-we-01
    jobs:
      - deployment: Deploy
        displayName: Add Sbx Key Vault Secrets
        environment: sbx
        strategy:
          runOnce:
            deploy:
              steps:
                - template: all-secrets.yml

  - stage: Dev
    displayName: Add Dev KV Secrets
    dependsOn: PublishArtifacts
    variables:
      - group: "Dev"
      - name: keyVaultName
        value: kv-cpd-apps-dev-we-01
    jobs:
      - deployment: Deploy
        displayName: Add dev Key Vault Secrets
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: all-secrets.yml

  - stage: Tst
    displayName: Add Tst KV Secrets
    dependsOn: PublishArtifacts
    variables:
      - group: "Tst"
      - name: keyVaultName
        value: kv-cpd-apps-tst-we-01
    jobs:
      - deployment: Deploy
        displayName: Add tst Key Vault Secrets
        environment: tst
        strategy:
          runOnce:
            deploy:
              steps:
                - template: all-secrets.yml

  - stage: Tra
    displayName: Add Tra KV Secrets
    dependsOn: PublishArtifacts
    variables:
      - group: "tra"
      - name: keyVaultName
        value: kv-cpd-apps-tra-we-01
    jobs:
      - deployment: Deploy
        displayName: Add tst Key Vault Secrets
        environment: tra
        strategy:
          runOnce:
            deploy:
              steps:
                - template: all-secrets.yml
