name: $(moduleName)-$(moduleVersion)

variables:
- template: /Modules/.global/global.variables.yml
- template: pipeline.variables.yml

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
    - Modules/ARM/AzureBastion/*
    exclude:
    - '*/readme.md'
    
stages:  
- stage: Scan
  jobs:
    - template: /Modules/.global/global.azsk.yml
      parameters:
        templateFile: $(modulePath)/deploy.json
        parametersFile: $(modulePath)/Parameters/parameters.json
          
- stage: Validation
  jobs:
  - template: pipeline.jobs.validate.yml
    parameters:
      templateFile: $(modulePath)/deploy.json
      parametersFile: $(modulePath)/Parameters/parameters.json

- stage: Publishing
  jobs:
  - template: pipeline.jobs.publish.yml

