jobs:
  - job: DisablePublicIPs
    steps:
      - task: AzureCLI@2
        displayName: "Disable Public IPs"
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: "pscore"
          scriptLocation: inlineScript
          inlineScript: |
            az acr update --name acrcpdglobnpdwe01 --public-network-enabled false