trigger: none
resources:
  repositories:
    - repository: platform-apis # The name used to reference this repository in the checkout step
      type: git
      name: TASMU Central Platform/platform-apis
      ref: master

    - repository: QC-Infra # The name used to reference this repository in the checkout step
      type: git
      name: QC-Infra
      ref: Ashok/PlatformApis

variables:
  namespace: "apiapps"
  vmImage: "ubuntu-latest"
  dockerRegistryServiceConnection: "acrcpdglobnpdwe02-spn"
  functionSolutionPath: "src/functions/*/*.sln"
  BuildConfiguration: "Release"
  BuildPlatform: "Any CPU"
  tag: "$(Build.BuildId)"
  serviceConnection: sqcp-ado-spn-dev

pool:
  vmImage: "$(vmImage)"
stages:
  # - stage: Enableacrpublicips
  #   displayName: Enableacrpublicips
  #   jobs:
  #     - template: templates/enable-acr-publicips.yml

  - stage: Build
    displayName: Build stage
    jobs:
      - template: templates/build-push-api.yml
        parameters:
          name: smsprovider
          solutionPath: "src/services/SmsProvider"

      - template: templates/build-push-api.yml
        parameters:
          name: smspublisher
          solutionPath: "src/services/SmsPublisher"

      - template: templates/build-push-api.yml
        parameters:
          name: notificationfunc
          solutionPath: "src/functions/Notification"
          namespace: "jobs"

      - template: templates/build-push-api.yml
        parameters:
          name: manageeventfunc
          solutionPath: "src/functions/ManageEvent"
          namespace: "jobs"

      - template: templates/build-push-api.yml
        parameters:
          name: fieldservicefunc
          solutionPath: "src/functions/FieldService"
          namespace: "jobs"

      - template: templates/build-push-api.yml
        parameters:
          name: knowledgebaseapi
          solutionPath: "src/services/Mcs.Tasmu.KnowledgebaseArticle.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: caseapi
          solutionPath: "src/services/Case"

      - template: templates/build-push-api.yml
        parameters:
          name: fieldserviceapi
          solutionPath: "src/services/FieldService"

      - template: templates/build-push-api.yml
        parameters:
          name: organisationprofileapi
          solutionPath: "src/services/Mcs.Tasmu.OrganisationProfile.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: profileapi
          solutionPath: "src/services/Mcs.Tasmu.Profile.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: marketplacecatalogueapi
          solutionPath: "src/services/Mcs.Tasmu.MarketplaceCatalogue.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: demographicapi
          solutionPath: "src/services/Mcs.Tasmu.Demographic.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: configapi
          solutionPath: "src/services/Mcs.Tasmu.Config.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: notificationapi
          solutionPath: "src/services/Notification"

      - template: templates/build-push-api.yml
        parameters:
          name: notificationtemplateapi
          solutionPath: "src/services/NotificationTemplate"

      - template: templates/build-push-api.yml
        parameters:
          name: smartparkingapi
          solutionPath: "src/services/Smartparking"

      - template: templates/build-push-api.yml
        parameters:
          name: cmscontentapi
          solutionPath: "src/services/Mcs.TASMU.CMS.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: cmsdocumentsapi
          solutionPath: "src/services/Mcs.TASMU.CMS.Documents.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: cmsmediaassetsapi
          solutionPath: "src/services/Mcs.TASMU.CMS.MediaAssets.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: paymentgwapi
          solutionPath: "src/services/Mcs.Tasmu.PaymentGW.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: subscriptionsapi
          solutionPath: "src/services/Mcs.Tasmu.Subscriptions.Api"

      - template: templates/build-push-api.yml
        parameters:
          name: backofficeapi
          solutionPath: "src/services/Mcs.Tasmu.BackOfficePortal.Api"

      # Add more template jobs with parameters for other Services

      # Build Function Apps
      - template: templates/build-funcapps.yml
        parameters:
          poolName: "tasmumsagents"

      # Publish Artifacts
      - template: templates/publish-artifacts.yml
        parameters:
          chartsPath: "pipelines/deploy/charts"
          poolName: "tasmumsagents"

  # - stage: Disableacrpublicips
  #   displayName: Disableacrpublicips
  #   jobs:
  #     - template: templates/disable-acr-publicips.yml        

  - stage: Deploy_dev
    displayName: Deploy dev stage
    dependsOn: Build
    variables:
      - group: Dev
      - name: azureResourceGroup
        value: "rg-cpd-apps-aks-dev-we-01"
      - name: kubernetesCluster
        value: "aks-cpd-apps-dev-we-01"
      - name: "enablehpa"
        value: "false"
      - name: containerRegistry
        value: "acrcpdglobnpdwe01.azurecr.io"
      - name: appConfigConnection
        value: "https://acst-cpd-apps-str-dev-we-01.azconfig.io"
      - name: podIdentity
        value: "mi-cpd-apps-aksnode-dev-we-01"
      - name: env
        value: "dev"
      - name: apiHost
        value: "api.dev.sqcp.qa"
      - name: paymentfunctionAppName
        value: "func-cpd-apps-pt-dev-we-01"
      - name: reconcileRefundFunctionApp
        value: "func-cpd-apps-rrf-dev-we-01"
      - name: ckanResourceCreationFunctionAppName
        value: "func-cpd-apps-ckan-dev-we-01"
      - name: consumptionfunctionApp
        value: "func-cpd-apps-acm-dev-we-01"
      - name: businessProcessfunctionApp
        value: "func-cpd-apps-intbpa-dev-we-01"
      - name: sharepointNotifyfunctionApp
        value: "func-cpd-apps-intntf-dev-we-01"
      - name: d365ProfilefunctionApp
        value: "func-cpd-apps-prflint-dev-we-01"
    pool:
      name: "tasmumsagents"
    jobs:
      - deployment: Deploy
        displayName: Deploy Dev APIs
        environment: "Dev"
        strategy:
          runOnce:
            deploy:
              steps:
                # - task: AzureCLI@2
                #   displayName: "Allow Public IPs"
                #   inputs:
                #     azureSubscription: $(serviceConnection)
                #     scriptType: "pscore"
                #     scriptLocation: inlineScript
                #     inlineScript: |
                #       az acr update --name acrcpdglobnpdwe01 --default-action Allow
                #       az acr update --name acrcpdglobnpdwe01 --public-network-enabled true

                - task: HelmInstaller@1
                  inputs:
                    helmVersionToInstall: "3.2.1"

                # - template: templates/deploy-dapr.yml
                #   parameters:
                #     installDapr: true
                #     azureSubscription: sqcp-ado-spn-dev

                - template: templates/deploy-apps.yml
                  parameters:
                    azureSubscription: sqcp-ado-spn-dev

                # - template: templates/deploy-funcapps.yml
                #   parameters:
                #     azureSubscription: sqcp-ado-spn-dev

                # - task: AzureCLI@2
                #   displayName: "Disable Public IPs"
                #   inputs:
                #     azureSubscription: $(serviceConnection)
                #     scriptType: "pscore"
                #     scriptLocation: inlineScript
                #     inlineScript: |
                #       az acr update --name acrcpdglobnpdwe01 --public-network-enabled false    

  # - stage: Deploy_tst
  #   displayName: Deploy tst stage
  #   dependsOn: Deploy_dev
  #   variables:
  #     - group: Tst
  #     - name: azureResourceGroup
  #       value: "rg-cpd-apps-aks-tst-we-01"
  #     - name: kubernetesCluster
  #       value: "aks-cpd-apps-tst-we-01"
  #     - name: "enablehpa"
  #       value: "true"
  #     - name: containerRegistry
  #       value: "acrcpdglobnpdwe01.azurecr.io"
  #     - name: appConfigConnection
  #       value: "https://acst-cpd-apps-str-tst-we-01.azconfig.io"
  #     - name: podIdentity
  #       value: "mi-cpd-apps-aksnode-tst-we-01"
  #     - name: env
  #       value: "tst"
  #     - name: apiHost
  #       value: "api.tst.sqcp.qa"
  #     - name: paymentfunctionAppName
  #       value: "func-cpd-apps-pt-tst-we-01"
  #     - name: reconcileRefundFunctionApp
  #       value: "func-cpd-apps-rrf-tst-we-01"
  #     - name: ckanResourceCreationFunctionAppName
  #       value: "func-cpd-apps-ckan-tst-we-01"        
  #     - name: consumptionfunctionApp
  #       value: "func-cpd-apps-acm-tst-we-01"
  #     - name: businessProcessfunctionApp
  #       value: "func-cpd-apps-intbpa-tst-we-01"
  #     - name: sharepointNotifyfunctionApp
  #       value: "func-cpd-apps-intntf-tst-we-01"
  #     - name: d365ProfilefunctionApp
  #       value: "func-cpd-apps-prflint-tst-we-01"
  #     - name: captchafunctionApp
  #       value: "func-cpd-apps-cpch-tst-we-01"
  #   pool:
  #     name: "testagentpool"
  #   jobs:
  #     - deployment: Deploy
  #       displayName: Deploy tst APIs
  #       environment: "tst"
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - task: AzureCLI@2
  #                 displayName: "Allow Public IPs"
  #                 inputs:
  #                   azureSubscription: $(serviceConnection)
  #                   scriptType: "pscore"
  #                   scriptLocation: inlineScript
  #                   inlineScript: |
  #                     az acr update --name acrcpdglobnpdwe01 --default-action Allow
  #                     az acr update --name acrcpdglobnpdwe01 --public-network-enabled true

  #               - task: HelmInstaller@1
  #                 inputs:
  #                   helmVersionToInstall: "3.2.1"

  #               - template: templates/deploy-dapr.yml
  #                 parameters:
  #                   installDapr: true
  #                   azureSubscription: sqcp-ado-spn-dev

  #               - template: templates/deploy-apps.yml
  #                 parameters:
  #                   azureSubscription: sqcp-ado-spn-dev

  #               - template: templates/deploy-funcapps.yml
  #                 parameters:
  #                   azureSubscription: sqcp-ado-spn-dev

  #               - task: AzureCLI@2
  #                 displayName: "Disable Public IPs"
  #                 inputs:
  #                   azureSubscription: $(serviceConnection)
  #                   scriptType: "pscore"
  #                   scriptLocation: inlineScript
  #                   inlineScript: |
  #                     az acr update --name acrcpdglobnpdwe01 --public-network-enabled false

  # - stage: Deploy_tra
  #   displayName: Deploy tra stage
  #   dependsOn: Deploy_tst
  #   variables:
  #     - group: tra
  #     - name: azureResourceGroup
  #       value: "rg-cpd-apps-aks-tra-we-01"
  #     - name: kubernetesCluster
  #       value: "aks-cpd-apps-tra-we-01"
  #     - name: "enablehpa"
  #       value: "false"
  #     - name: containerRegistry
  #       value: "acrcpdglobnpdwe01.azurecr.io"
  #     - name: appConfigConnection
  #       value: "https://acst-cpd-apps-str-tra-we-01.azconfig.io"
  #     - name: podIdentity
  #       value: "mi-cpd-apps-aksnode-tra-we-01"
  #     - name: env
  #       value: "tra"
  #     - name: apiHost
  #       value: "api.trn.sqcp.qa"
  #     - name: paymentfunctionAppName
  #       value: "func-cpd-apps-pt-tra-we-01"
  #     - name: reconcileRefundFunctionApp
  #       value: "func-cpd-apps-rrf-tra-we-01"
  #     - name: consumptionfunctionApp
  #       value: "func-cpd-apps-acm-tra-we-01"
  #     - name: businessProcessfunctionApp
  #       value: "func-cpd-apps-intbpa-tra-we-01"
  #     - name: sharepointNotifyfunctionApp
  #       value: "func-cpd-apps-intntf-tra-we-01"
  #     - name: d365ProfilefunctionApp
  #       value: "func-cpd-apps-prflint-tra-we-01"
  #   pool:
  #     name: "testagentpool"
  #   jobs:
  #     - deployment: Deploy
  #       displayName: Deploy tra APIs
  #       environment: "tra"
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - task: AzureCLI@2
  #                 displayName: "Allow Public IPs"
  #                 inputs:
  #                   azureSubscription: $(serviceConnection)
  #                   scriptType: "pscore"
  #                   scriptLocation: inlineScript
  #                   inlineScript: |
  #                     az acr update --name acrcpdglobnpdwe01 --default-action Allow
  #                     az acr update --name acrcpdglobnpdwe01 --public-network-enabled true

  #               - task: HelmInstaller@1
  #                 inputs:
  #                   helmVersionToInstall: "3.2.1"

  #               - template: templates/deploy-dapr.yml
  #                 parameters:
  #                   installDapr: true
  #                   azureSubscription: sqcp-ado-spn-dev

  #               - template: templates/deploy-apps.yml
  #                 parameters:
  #                   azureSubscription: sqcp-ado-spn-dev

  #               - template: templates/deploy-funcapps.yml
  #                 parameters:
  #                   azureSubscription: sqcp-ado-spn-dev

  #               - task: AzureCLI@2
  #                 displayName: "Disable Public IPs"
  #                 inputs:
  #                   azureSubscription: $(serviceConnection)
  #                   scriptType: "pscore"
  #                   scriptLocation: inlineScript
  #                   inlineScript: |
  #                     az acr update --name acrcpdglobnpdwe01 --public-network-enabled false

  # - stage: Deploy_uat
  #   displayName: Deploy uat stage
  #   dependsOn: Deploy_tst
  #   variables:
  #     - group: uat
  #     - name: azureResourceGroup
  #       value: "rg-cpd-apps-aks-uat-we-01"
  #     - name: kubernetesCluster
  #       value: "aks-cpd-apps-uat-we-01"
  #     - name: "enablehpa"
  #       value: "true"
  #     - name: containerRegistry
  #       value: "acrcpdglobnpdwe01.azurecr.io"
  #     - name: appConfigConnection
  #       value: "https://acst-cpd-apps-str-uat-we-01.azconfig.io"
  #     - name: podIdentity
  #       value: "mi-cpd-apps-aksnode-uat-we-01"
  #     - name: env
  #       value: "uat"
  #     - name: apiHost
  #       value: "api.uat.sqcp.qa"
  #     - name: paymentfunctionAppName
  #       value: "func-cpd-apps-pt-uat-we-01"
  #     - name: reconcileRefundFunctionApp
  #       value: "func-cpd-apps-rrf-uat-we-01"
  #     - name: consumptionfunctionApp
  #       value: "func-cpd-apps-acm-uat-we-01"
  #     - name: businessProcessfunctionApp
  #       value: "func-cpd-apps-intbpa-uat-we-01"
  #     - name: sharepointNotifyfunctionApp
  #       value: "func-cpd-apps-intntf-uat-we-01"
  #     - name: ckanResourceCreationFunctionAppName
  #       value: "func-cpd-apps-ckan-uat-we-01"
  #     - name: d365ProfilefunctionApp
  #       value: "func-cpd-apps-prflint-uat-we-01"
  #     - name: captchafunctionApp
  #       value: "func-cpd-apps-cpch-uat-we-01"
  #   pool:
  #     name: "testagentpool"
  #   jobs:
  #     - deployment: Deploy
  #       displayName: Deploy uat APIs
  #       environment: "uat"
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - task: AzureCLI@2
  #                 displayName: "Allow Public IPs"
  #                 inputs:
  #                   azureSubscription: $(serviceConnection)
  #                   scriptType: "pscore"
  #                   scriptLocation: inlineScript
  #                   inlineScript: |
  #                     az acr update --name acrcpdglobnpdwe01 --default-action Allow
  #                     az acr update --name acrcpdglobnpdwe01 --public-network-enabled true

  #               - task: HelmInstaller@1
  #                 inputs:
  #                   helmVersionToInstall: "3.2.1"

  #               - template: templates/deploy-dapr.yml
  #                 parameters:
  #                   installDapr: true
  #                   azureSubscription: sqcp-ado-spn-dev

  #               - template: templates/deploy-apps.yml
  #                 parameters:
  #                   azureSubscription: sqcp-ado-spn-dev

  #               - template: templates/deploy-funcapps.yml
  #                 parameters:
  #                   azureSubscription: sqcp-ado-spn-dev

  #               - task: AzureRmWebAppDeployment@4
  #                 displayName: Deploy $(ckanResourceCreationFunctionAppName)
  #                 continueOnError: true
  #                 inputs:
  #                   ConnectionType: "AzureRM"
  #                   azureSubscription: sqcp-ado-spn-dev
  #                   appType: "functionApp"
  #                   WebAppName: $(ckanResourceCreationFunctionAppName)
  #                   packageForLinux: "$(Pipeline.Workspace)/functionapps/CkanResourceCreationFunction.zip"

  #               - task: AzureCLI@2
  #                 displayName: "Disable Public IPs"
  #                 inputs:
  #                   azureSubscription: $(serviceConnection)
  #                   scriptType: "pscore"
  #                   scriptLocation: inlineScript
  #                   inlineScript: |
  #                     az acr update --name acrcpdglobnpdwe01 --public-network-enabled false