# To be run view Arabic User account only
trigger: none
pool: 'tasmumsagents'
jobs:
- job: ArabicNavandTitleUpdation
  timeoutInMinutes: 240
  steps:     
  - task: PowerShell@2
    inputs:
     targetType: "filePath"
     filePath: '$(Build.SourcesDirectory)\Scripts\CMS\ProvisioningScripts\PnP.Powershell\createArabicNavandTitle.ps1'
     arguments: "-tenant $(tenant) -sp_user $(sp_user) -sp_password $(sp_password) -InstrumentationKey $(instrumentationkey)"
