
trigger: none
pool: 'tasmumsagents'
jobs:
- job: GetBase64
  timeoutInMinutes: 240
  steps: 
  - task: DownloadSecureFile@1
    name: "PfxFile"
    inputs:
      secureFile: "$(PfxFileName)"

  - task: PowerShell@2
    inputs:
     targetType: "filePath"
     filePath: '$(Build.SourcesDirectory)\Scripts\CMS\ProvisioningScripts\PnP.Powershell\Base64.ps1'
     arguments: "-filePath $(PfxFile.secureFilePath) -tenant $(tenant) -sp_user $(sp_user) -sp_password $(sp_password)"