# Starter pipeline
trigger: none
pool: 'tasmumsagents'
jobs:
- job: Provisioning
  timeoutInMinutes: 240
  steps:
  - powershell: |
     Write-Host "This works: $env:MY_MAPPED_ENV_VAR"    # Recommended
     Write-Host "$env:SYSTEM_DEFAULTWORKINGDIRECTORY"
     Write-Host "enviromnment variable path $env:MAPPED_ENV_VAR"
     Write-Host "$(Build.SourcesDirectory)"
     
  - task: PowerShell@2
    inputs:
     targetType: "filePath"
     filePath: '$(Build.SourcesDirectory)\Scripts\CMS\ProvisioningScripts\PnP.Powershell\pnppowershellprerequisites.ps1'
