# To be run view Arabic User account only
trigger: none
pool: 'tasmumsagents'
jobs:
- job: Updation_of_Resource_File
  steps:     
  - task: PowerShell@2
    inputs:
     targetType: "filePath"
     filePath: '$(Build.SourcesDirectory)\Scripts\CMS\ProvisioningScripts\PnP.Powershell\UpdateResx.ps1'
   
