
trigger: none
pool: 'tasmumsagents'
jobs:
- job: UpdateResourceFiles
  timeoutInMinutes: 240
  steps: 
  - task: PowerShell@2
    inputs:
     targetType: "filePath"
     filePath: '$(Build.SourcesDirectory)\Scripts\CMS\ProvisioningScripts\UpdateResx.ps1'
     arguments: "-tenant $(tenant) -sp_user $(sp_user) -sp_password $(sp_password)"