name: $(moduleName)-$(moduleVersion)

variables:
- template: pipeline.variables.yml
- template: /Modules/.global/global.variables.yml

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
    - Modules/NotificationHubNamespaces/*
    exclude:
    - Modules/NotificationHubNamespaces/*/readme.md
    
stages:

- stage: Validate
  jobs:
  - template: pipeline.jobs.validate.yml
    parameters:
      templateFile: $(modulePath)/deploy.json
      parametersFile: $(modulePath)/Parameters/parameters.json

- stage: Publish_Artifact
  jobs:
  - template: pipeline.jobs.publish.yml
