jobs:
  - job: PublishArtifact
    displayName: Publish Artifact
    pool:
      name: $(poolName)
      # vmImage: $(vmImage)
      
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: PublishBuildArtifacts@1
        displayName: Publish $(moduleName) Artifacts
        inputs:
          PathtoPublish: $(modulePath)
          ArtifactName: $(moduleName)-$(moduleVersion)

  - job: PublishComponentPrd
    displayName: Publish Component Prd
    pool:
      name: $(poolName)
      # vmImage: $(vmImage)
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: CopyFiles@2
        displayName: Filter folders
        inputs:
          Contents: |
            Modules/ARM/$(moduleName)/$(moduleVersion)/**
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: AzureCLI@1
        displayName: Create container $(componentStorageContainerName)
        inputs:
          azureSubscription: $(serviceConnectionPrd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNamePrd)" --subscription "$(componentStorageAccountSubscriptionIdPrd)"           
        
      - task: AzureCLI@1
        displayName: Copy Module to $(componentStorageAccountNamePrd)
        inputs:
          azureSubscription: $(serviceConnectionPrd)
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNamePrd)" --subscription  "$(componentStorageAccountSubscriptionIdPrd)"

  # - job: PublishComponentPre
  #   displayName: Publish Component Pre
  #   pool:
  #     #name: $(poolName)
  #     vmImage: $(vmImage)
  #   variables:
  #     - template: pipeline.variables.yml
  #   steps:
  #     - task: CopyFiles@2
  #       displayName: Filter folders
  #       inputs:
  #         Contents: |
  #           Modules/ARM/$(moduleName)/$(moduleVersion)/**
  #         targetFolder: $(Build.ArtifactStagingDirectory)
  #     - task: AzureCLI@1
  #       displayName: Create container $(componentStorageContainerName)
  #       inputs:
  #         azureSubscription: $(serviceConnectionPrd)
  #         scriptLocation: inlineScript
  #         inlineScript: |
  #           az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNamePre)" --subscription "$(componentStorageAccountSubscriptionIdPrd)"

  #     - task: AzureCLI@1
  #       displayName: Copy Module to $(componentStorageAccountNamePre)
  #       inputs:
  #         azureSubscription: $(serviceConnectionPrd)
  #         scriptLocation: inlineScript
  #         inlineScript: |
  #           az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNamePre)" --subscription  "$(componentStorageAccountSubscriptionIdPrd)"

  # - job: PublishComponentNpd
  #   displayName: Publish Component Npd
  #   pool:
  #     #name: $(poolName)
  #     vmImage: $(vmImage)
  #   variables:
  #     - template: pipeline.variables.yml
  #   steps:
  #     - task: CopyFiles@2
  #       displayName: Filter folders
  #       inputs:
  #         Contents: |
  #           Modules/ARM/$(moduleName)/$(moduleVersion)/**
  #         targetFolder: $(Build.ArtifactStagingDirectory)
  #     - task: AzureCLI@1
  #       displayName: Create container $(componentStorageContainerName)
  #       inputs:
  #         azureSubscription: $(serviceConnectionNpd)
  #         scriptLocation: inlineScript
  #         inlineScript: |
  #           echo "I am here"
  #           echo $componentStorageAccountSubscriptionIdNpd         
  #           az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNameNpd)" --account-key "$(account-key)" --subscription "$(componentStorageAccountSubscriptionIdNpd)"           
        
  #     - task: AzureCLI@1
  #       displayName: Copy Module to $(componentStorageAccountNameNpd)
  #       inputs:
  #         azureSubscription: $(serviceConnectionNpd)
  #         scriptLocation: inlineScript
  #         inlineScript: |
  #           az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "components/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name  "$(componentStorageAccountNameNpd)" --account-key "$(account-key)" --subscription "$(componentStorageAccountSubscriptionIdNpd)"

#   - job: PublishComponentCOPPrd
#     displayName: Publish Component COP PRD
#     pool:
#       #name: $(poolName)
#       vmImage: $(vmImage)
#     variables:
#       - template: pipeline.variables.yml
#     steps:
#       - task: CopyFiles@2
#         displayName: Filter folders
#         inputs:
#           Contents: |
#             Modules/ARM/$(moduleName)/$(moduleVersion)/**
#           targetFolder: $(Build.ArtifactStagingDirectory)
#       - task: AzureCLI@1
#         displayName: Create container $(componentStorageContainerName)
#         inputs:
#           azureSubscription: $(serviceConnectionCOPPrd)
#           scriptLocation: inlineScript
#           inlineScript: |
#             az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNameCOPPrd)" --subscription "$(componentStorageAccountSubscriptionIdCOPPrd)"           
        
#       - task: AzureCLI@1
#         displayName: Copy Module to $(componentStorageAccountNameCOPPrd)
#         inputs:
#           azureSubscription: $(serviceConnectionCOPPrd)
#           scriptLocation: inlineScript
#           inlineScript: |
#             az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNameCOPPrd)" --subscription  "$(componentStorageAccountSubscriptionIdCOPPrd)"

#   - job: PublishComponentScalePrd
#     displayName: Publish Component Scale PRD
#     pool:
#       #name: $(poolName)
#       vmImage: $(vmImage)
#     variables:
#       - template: pipeline.variables.yml
#     steps:
#       - task: CopyFiles@2
#         displayName: Filter folders
#         inputs:
#           Contents: |
#             Modules/ARM/$(moduleName)/$(moduleVersion)/**
#           targetFolder: $(Build.ArtifactStagingDirectory)
#       - task: AzureCLI@1
#         displayName: Create container $(componentStorageContainerName)
#         inputs:
#           azureSubscription: $(serviceConnectionSCALEPrd)
#           scriptLocation: inlineScript
#           inlineScript: |
#             az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNameSCALEPRD)" --subscription "$(componentStorageAccountSubscriptionIdSCALEPrd)"           
        
#       - task: AzureCLI@1
#         displayName: Copy Module to $(componentStorageAccountNameCOPPrd)
#         inputs:
#           azureSubscription: $(serviceConnectionSCALEPrd)
#           scriptLocation: inlineScript
#           inlineScript: |
#             az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNameSCALEPRD)" --subscription  "$(componentStorageAccountSubscriptionIdSCALEPrd)"

#   - job: PublishComponentVSEEPrd
#     displayName: Publish Component VSEE PRD
#     pool:
#       #name: $(poolName)
#       vmImage: $(vmImage)
#     variables:
#       - template: pipeline.variables.yml
#     steps:
#       - task: CopyFiles@2
#         displayName: Filter folders
#         inputs:
#           Contents: |
#             Modules/ARM/$(moduleName)/$(moduleVersion)/**
#           targetFolder: $(Build.ArtifactStagingDirectory)
#       - task: AzureCLI@1
#         displayName: Create container $(componentStorageContainerName)
#         inputs:
#           azureSubscription: $(serviceConnectionVSEEPrd)
#           scriptLocation: inlineScript
#           inlineScript: |
#             az storage container create --name "$(componentStorageContainerName)" --public-access off --account-name  "$(componentStorageAccountNameVSEEPRD)" --account-key "$(account-key-vsee)" --subscription "$(componentStorageAccountSubscriptionIdVSEEPrd)"           
        
#       - task: AzureCLI@1
#         displayName: Copy Module to $(componentStorageAccountNameCOPPrd)
#         inputs:
#           azureSubscription: $(serviceConnectionVSEEPrd)
#           scriptLocation: inlineScript
#           inlineScript: |
#             az storage blob upload-batch --source "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" --destination "$(componentStorageContainerName)/Modules/ARM/$(moduleName)/$(moduleVersion)" --account-name "$(componentStorageAccountNameVSEEPRD)" --account-key "$(account-key-vsee)" --subscription  "$(componentStorageAccountSubscriptionIdVSEEPrd)"