trigger:
  batch: true
  branches:
    include:
      - master

  paths:
    include:
      - Scripts/AppConfigurations/keyvaultref/*
      - Scripts/AppConfigurations/settings/*

variables:
  - name: PoolName
    value: "testagentpool"
  - name: azureSubscription
    value: sqcp-ado-spn-dev
pool:
  name: $(PoolName)

stages:
  - stage: PublishArtifacts
    jobs:
      - job: PublishArtifacts
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: Scripts/AppConfigurations
              Contents: "**"
              TargetFolder: "$(build.artifactstagingdirectory)/configurations"
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: Scripts/AppConfigurations
              artifact: "configurations"
              publishLocation: "pipeline"

  - stage: Sbx
    displayName: Update App Configurations for sbx
    dependsOn: PublishArtifacts
    variables:
      - name: appConfigName
        value: "acst-cpd-apps-sbx-we-01"
      - name: aksResourceGroupName
        value: "rg-cpd-apps-sbx-we-01"
      - name: aksClusterName
        value: "aks-cpd-apps-sbx-we-01"
      - name: env
        value: "sbx"
    jobs:
      - deployment: Deploy
        displayName: Update App Configurations for sbx
        environment: sbx
        strategy:
          runOnce:
            deploy:
              steps:
                - template: update-app-config.yml
                - template: restart-pods.yml
  - stage: Dev
    displayName: Update App Configurations for dev
    dependsOn: PublishArtifacts
    variables:
      - name: appConfigName
        value: "acst-cpd-apps-dev-we-01"
      - name: aksResourceGroupName
        value: "rg-cpd-apps-dev-we-01"
      - name: aksClusterName
        value: "aks-cpd-apps-dev-we-01"
      - name: env
        value: "dev"
    jobs:
      - deployment: Deploy
        displayName: Update App Configurations for dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: update-app-config.yml
                - template: restart-pods.yml
  - stage: Tst
    displayName: Update App Configurations for tst
    dependsOn: Dev
    variables:
      - name: appConfigName
        value: "acst-cpd-apps-tst-we-01"
      - name: aksResourceGroupName
        value: "rg-cpd-apps-tst-we-01"
      - name: aksClusterName
        value: "aks-cpd-apps-tst-we-01"
      - name: env
        value: "tst"
    jobs:
      - deployment: Deploy
        displayName: Update App Configurations for tst
        environment: tst
        strategy:
          runOnce:
            deploy:
              steps:
                - template: update-app-config.yml
                - template: restart-pods.yml

  - stage: uat
    displayName: Update App Configurations for uat
    dependsOn: Tst
    variables:
      - name: appConfigName
        value: "acst-cpd-apps-str-uat-we-01"
      - name: aksResourceGroupName
        value: "rg-cpd-apps-aks-uat-we-01"
      - name: aksClusterName
        value: "aks-cpd-apps-uat-we-01"
      - name: env
        value: "uat"
    jobs:
      - deployment: Deploy
        displayName: Update App Configurations for uat
        environment: uat
        strategy:
          runOnce:
            deploy:
              steps:
                - template: update-app-config.yml
                - template: restart-pods.yml
