trigger:
  batch: true
  branches:
    include:
      - master

  paths:
    include:
      - Scripts/AppConfigurations/keyvaultref/*
      - Scripts/AppConfigurations/settings/*

variables:
  - name: PoolName
    value: "tasmumsagents"
  - name: azureSubscription
    value: sqcp-ado-spn-dev
pool:
  name: $(PoolName)

stages:
  - stage: PublishArtifacts
    jobs:
    - job: PublishArtifacts
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: Scripts/AppConfigurations
          Contents: "**"
          TargetFolder: "$(build.artifactstagingdirectory)/configurations"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: Scripts/AppConfigurations
          artifact: "configurations"
          publishLocation: "pipeline"

  - stage: Sbx
    displayName: Add Sandbox KV Secrets
    dependsOn: PublishArtifacts
    variables:
      - name: appConfigName
        value: "acst-cpd-apps-sbx-we-01"
      - name: env
        value: "sbx"    
    jobs:
      - deployment: Deploy
        displayName: Update App Configurations for sbx
        environment: sbx
        strategy:
          runOnce:
            deploy:
              steps:
                - template: update-app-config.yml

  - stage: Dev
    displayName: Update App Configurations for dev
    dependsOn: Sbx
    variables:
      - name: appConfigName
        value: "acst-cpd-apps-dev-we-01"
      - name: env
        value: "dev"   
    jobs:
      - deployment: Deploy
        displayName: Update App Configurations for dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: update-app-config.yml

  - stage: Tst
    displayName: Update App Configurations for tst
    dependsOn: Dev
    variables:
      - name: appConfigName
        value: "acst-cpd-apps-tst-we-01"
      - name: env
        value: "tra"   
    jobs:
      - deployment: Deploy
        displayName: Update App Configurations for tst
        environment: tst
        strategy:
          runOnce:
            deploy:
              steps:
                - template: update-app-config.yml

  - stage: Tra
    displayName: Update App Configurations for tra
    dependsOn: Tst
    variables:
      - name: appConfigName
        value: "acst-cpd-apps-tra-we-01"
      - name: env
        value: "tra"   
    jobs:
      - deployment: Deploy
        displayName: Update App Configurations for tra
        environment: tra
        strategy:
          runOnce:
            deploy:
              steps:
                - template: update-app-config.yml
