name: $(resourceGroupName)

variables:
  - name: PoolName
    value: "tasmumsagents"
  - name: templateFilePath
    value: DeploymentOrchestration/Environments/CPD/TRA/rg-cpd-apps-sec-tra-we-01/deploy.json
  - name: parameterFilePath
    value:
  - name: location
    value: westeurope
  - name: resourceGroupName
    value: rg-cpd-apps-sec-tra-we-01
  - name: serviceConnection
    value: sqcp-ado-spn-dev
  - name: subscriptionId
    value: d0694def-b27e-4bb7-900d-437fbeb802da

trigger: none
#trigger:
#  batch: true
#  branches:
#    include:
#      - master
#  paths:
#    include:
#    - DeploymentOrchestration/TemplateBased/ARM/Contoso-private-hub/*

stages:
  - stage: Validate
    jobs:
      - job: ValidateTemplate
        displayName: Validate Template
        pool:
          name: $(PoolName)
        steps:
          - task: AzurePowerShell@4
            displayName: Validate template on $(resourceGroupName)
            inputs:
              azureSubscription: $(serviceConnection)
              ScriptType: InlineScript
              inline: |
                $ValidationErrors = $null

                $Location = "$(location)" -replace " ",""

                $DeploymentInputs = @{
                  Location              = "$Location"
                  TemplateFile          = "$(Build.Repository.LocalPath)/$(templateFilePath)"
                  # TemplateParameterFile = "$(Build.Repository.LocalPath)/$(parameterFilePath)"
                  Verbose               = $true
                  OutVariable           = "ValidationErrors"
                }

                Test-AzDeployment @DeploymentInputs

                if ($ValidationErrors)
                {
                  Write-Error "Template is not valid."
                }
              azurePowerShellVersion: LatestVersion

  - stage: DeployTemplate
    jobs:
      - job: DeployTemplate
        displayName: Deploy Template
        pool:
          name: $(PoolName)
        steps:
          - task: AzurePowerShell@4
            displayName: Deploy template on $(resourceGroupName)
            inputs:
              azureSubscription: $(serviceConnection)
              ScriptType: InlineScript
              inline: |
                $Location = "$(location)" -replace " ",""

                $DeploymentInputs = @{
                  Name                    = "$(resourceGroupName)-master"
                  Location                = "$Location"
                  TemplateFile            = "$(Build.Repository.LocalPath)/$(templateFilePath)"
                  # TemplateParameterFile  = "$(Build.Repository.LocalPath)/$(parameterFilePath)"
                  DeploymentDebugLogLevel = "All"
                  Verbose                 = $true
                  ErrorAction             = "Stop"
                }
                New-AzDeployment @DeploymentInputs
              azurePowerShellVersion: LatestVersion

  - stage: SecurityVerification
    jobs:
      - job: ScanResourceGroup
        displayName: Scan Resource Group
        pool:
          name: $(PoolName)
        steps:
          - task: AzSKSVTs@4
            displayName: Scan $(resourceGroupName)
            continueOnError: true
            inputs:
              ConnectedServiceNameARM: '$(serviceConnection)'
              GenerateMethodParameterSetSelection: 'ResourceGroupName'
              ResourceGroupName: '$(resourceGroupName)'
              SubscriptionId: '$(subscriptionId)'
