parameters:
  templateFile: $(modulePath)/deploy.json
  parametersFile: $(modulePath)/deploy.parameters.json

jobs:
- job: ValidateModule
  displayName: Validate Module
  pool:
    #name: $(PoolName)
    vmImage: $(vmImage)
  variables:
  - template: azure-pipelines.variables.yml
  steps:
    
    - task: AzurePowerShell@5 #DeployArcGisServer 
      displayName: 'DeployArcGisServer $(moduleName) in $(resourceGroupName) via $(serviceconnection)'
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        inline: |
          Write-Host "Build.Repository.LocalPath contents:"
          gci $(Build.Repository.LocalPath)/$(modulePath)
          Write-Host "################"
          $ValidationErrors = $null
          $scriptInputs = @{
              StorageAccountName        = "stcppgisstgprewe03"
              ResourceGroupName			    = "$(resourceGroupName)"
              #ResourceGroupLocation     = 'westeurope'
              TemplateFile              = "$(Build.Repository.LocalPath)/${{ parameters.templateFile }}" 
              TemplateParametersFile    = "$(Build.Repository.LocalPath)/${{ parameters.parametersFile }}" 
              ArtifactStagingDirectory  = "$(Build.Repository.LocalPath)/$(modulePath)"
              DSCSourceFolder           = "$(Build.Repository.LocalPath)/$(modulePath)"
              UploadArtifacts           = $true
              ValidateOnly              = $true
              DebugMode                 = $true
              OutVariable               = "ValidationErrors"
            }			
          $(Build.Repository.LocalPath)/$(modulePath)/deployArcGISSite.ps1 @scriptInputs

          if ($ValidationErrors)
            {
                foreach ($message in $ValidationErrors.Details)
                {
                    Write-Error $message.Message
                }
                Write-Error "Template is not valid."
            }
        azurePowerShellVersion: LatestVersion