# To be run view Schema Test Result list in global site collection only
trigger: none
pool: 'tasmumsagents'
jobs:
- job: SchemaTest
  timeoutInMinutes: 240
  steps:     
  - task: PowerShell@2
    inputs:
     targetType: "filePath"
     filePath: '$(Build.SourcesDirectory)\Scripts\CMS\ProvisioningScripts\testschema.ps1'
     arguments: "-tenant $(tenant) -sp_user $(sp_user) -sp_password $(sp_password) -InstrumentationKey $(instrumentationkey)"
