# To be used to resolve the translation file error
trigger: none
pool: 'tasmumsagents'
jobs:
- job: TranslationFileErrorResolution
  timeoutInMinutes: 240
  steps:     
  - task: PowerShell@2
    inputs:
     targetType: "filePath"
     filePath: '$(Build.SourcesDirectory)\Scripts\CMS\ProvisioningScripts\translationIssue.ps1'
     arguments: "-tenant $(tenant) -sp_user $(sp_user) -sp_password $(sp_password) -InstrumentationKey $(instrumentationkey)"
