jobs:
- job: PublishArtifact
  pool:
    # name: $(PoolName)
    vmImage: $(vmImage)
  variables:
  - template: pipeline.variables.yml
  steps:
    - task: PublishBuildArtifacts@1
      displayName: Publish $(moduleName) Artifacts
      inputs:
        PathtoPublish: $(modulePath)
        ArtifactName: $(moduleName)-$(moduleVersion)
- job: CreateComponent
  pool:
    vmImage: $(vmImage)
  variables:
  - template: pipeline.variables.yml
  steps:
    - task: CopyFiles@2
      displayName: Filter folders
      inputs:
        Contents: |
          Modules/ARM/$(moduleName)/$(moduleVersion)/**
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: AzureCLI@1
      displayName: Copy Module to $(componentStorageAccountNamePrd)
      inputs:
        azureSubscription: $(serviceConnectionPrdProd)
        scriptLocation: inlineScript
        inlineScript: |
            az storage container create --name          "$(componentStorageContainerName)" \
                                        --public-access off \
                                        --account-name  "$(componentStorageAccountNamePrdProd)" \
                                        --subscription  "$(componentStorageAccountSubscriptionIdPrdProd)"
                                        
            az storage blob sync --container    "$(componentStorageContainerName)" \
                                 --source       "$(Build.ArtifactStagingDirectory)/Modules/ARM/$(moduleName)/$(moduleVersion)" \
                                 --destination  "Modules/ARM/$(moduleName)/$(moduleVersion)" \
                                 --account-name "$(componentStorageAccountNamePrdProd)" \
                                 --subscription  "$(componentStorageAccountSubscriptionIdPrdProd)"