name: CD-APIMConfig-dev-Release

trigger: none

variables:
  - name: poolName
    value: "tasmumsagents"
  - name: templateFilePath
    value: deployment/pipeline/apim-deploy.json
  - name: componentStorageAccountId
    value: "/subscriptions/4e865dba-bf2f-463a-a957-c69f5fb32ec5/resourceGroups/rg-cph-pltf-iactst-prd-qc-01/providers/Microsoft.Storage/storageAccounts/stcphpltfiactstprdqc01"
  - name: location
    value: qatarcentral
  - name: serviceConnection
    value: sqcp-ado-spn-hub-qc

stages:
  - stage: DeployDEV
    displayName: Deploy DEV stage
    variables:
      - name: environment
        value: dev
      - name: resourceGroupName
        value: rg-integ-api-dev-qc-01
      - name: apimName
        value: apim-shared-integ-dev-qc-01
    jobs:
      - job: Build_Queue
        pool:
          name: $(poolName)
        steps:
          - task: PowerShell@2
            name: setBuildQueue
            inputs:
              targetType: filePath
              filePath: "deployment/pipeline/templates/get-service-queue.ps1"
            displayName: "Get Service Build Queue"

      - template: ./templates/apim-apis.yml
