apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
  namespace: apiapps
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    value: {{ .Values.environment.ConnectionString__ServiceBus}} # Required.