jobs:
  - job:
    displayName: "Deploy Alerts"
    pool:
      vmImage: $(vmImage)
    variables:
      - template: pipeline.variables.yml
    steps:
      - task: AzureCLI@2
        displayName: 'Deploy Alert'
        inputs:
            azureSubscription: $(serviceConnectionPrd)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
                az deployment group create --resource-group rg-cph-mgmt-net-prd-qc-01 --name healthalerts9 \
                --template-file $(modulePath)/deploy.json --parameters @'$(modulePath)/Parameters/alt-cph-metrics-mgmtonpfw-SNAT.parameters.json'
