#Note: Azure DevOps template does not have an equivalent in GitHub Actions yet
#Note: Azure DevOps template does not have an equivalent in GitHub Actions yet
name: Build
on:
  workflow_dispatch:
  push:
    branches:
    - none
    paths:
    - Modules/ARM/NetworkSecurityGroups/*
jobs:
  push_to_registry:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
    
      # - name: Validate
      #   uses: actions/checkout@v3
      #   with:
      #     repository: ${{ github.repository }}
      #     ref: ${{ github.sha }}
    
      # - name: Publish
      #   uses: actions/checkout@v3
      #   with:
      #     repository: ${{ github.repository }}
      #     ref: ${{ github.sha }}
      #     file : pipeline.jobs.publish.yml   
         
