#Note: Azure DevOps template does not have an equivalent in GitHub Actions yet
#Note: Azure DevOps template does not have an equivalent in GitHub Actions yet
name: ${{ env.moduleName }}-${{ env.moduleVersion }}
on:
  workflow_dispatch:
  push:
    branches:
     - none
    paths:
    - Modules/ARM/NetworkSecurityGroups/*
jobs:
  push_to_registry:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Validate
        uses: actions/checkout@v3
        with:
          context: .
          file : pipeline.jobs.validate.yml
          templateFile: Modules/ARM/NetworkSecurityGroups/2019-11-28/deploy.json
          parametersFile: Modules/ARM/NetworkSecurityGroups/2019-11-28/Parameters/parameters.json

      - name: Publish
        uses: actions/checkout@v3
        with:
           context: .
           file : pipeline.jobs.publish.yml   
     
