on:
  workflow_dispatch:
  push:
    branches:
    - none
    
name: $(moduleName)-$(moduleVersion)

variables:
  - template: pipeline.variables.yml
  - template: /Modules/.global/global.variables.yml

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - Modules/ARM/NetworkSecurityGroups/*
    exclude:
      - Modules/ARM/NetworkSecurityGroups/**/readme.md

stages:
  - stage: Validate
    jobs:
      job:
      - template: pipeline.jobs.validate.yml
        parameters:
          templateFile: $(modulePath)/deploy.json
          parametersFile: $(modulePath)/Parameters/parameters.json

  - stage: Publish
    jobs:
      job:
      - template: pipeline.jobs.publish.yml
